### ISSUE TITLE
[Bug] Swapped frequency and time step in info dict from sim script

### ISSUE THREAD

**Issue by j-kelm** [utiasDSL/lsy_drone_racing#11]
There seems to be a minor bug in the info dict from the simulation script, the control time step and frequency are swapped

https://github.com/utiasDSL/lsy_drone_racing/blob/4bb0f60232e27429b6e97fc75ac7f3d0fd059c1e/scripts/sim.py#L70
https://github.com/utiasDSL/lsy_drone_racing/blob/4bb0f60232e27429b6e97fc75ac7f3d0fd059c1e/scripts/sim.py#L71

**Comment by amacati** [comment]
Closed because it should be addressed in the major refactoring
