### ISSUE TITLE
[Enhancement] Support multiple action types

### ISSUE THREAD

**Issue by j-kelm** [utiasDSL/lsy_drone_racing#12]
Currently, only actions in the form of `[x, y, z, yaw]` are supported.

However, there might be controllers (like the MPC I am working on) that might want to provide all of the information for fullSateCommand, namely `[x, x_dot, x_ddot, y, y_dot, y_ddot, z, z_dot, z_ddot, yaw, roll_dot, pitch_dot, yaw_dot, body rates (p, q, r)]` (order is just an example) or even direct thrust values.

I understand that especially the direct trust values are difficult to implement gracefully, since:
1. Direct thrust control cannot reasonably be deployed on real hardware
2. One would omit the firmware controller implemented in the Drone class, which has impacts on the simulation

My fork currently contains a little hacky version of these features using a lot of if-statements, but I think that especially the full state command can be implemented in a clean way, e.g. having the base env take the full actions and provide a wrapper to reduce it to simplified form if desired.

**Comment by amacati** [comment]
Full state commands are now the default https://github.com/utiasDSL/lsy_drone_racing/blob/5d1d942ddc45a3d0d9027136cb7aeeb5167bd8cc/lsy_drone_racing/envs/drone_racing_env.py#L154-L165

Attitude controllers are supported with the new attitude interface of the DroneRacingThrustEnv
https://github.com/utiasDSL/lsy_drone_racing/blob/5d1d942ddc45a3d0d9027136cb7aeeb5167bd8cc/lsy_drone_racing/envs/drone_racing_env.py#L315-L322
