### ISSUE TITLE
[Bug] Mellinger controller stops working correctly when yaw is not close to zero

### ISSUE THREAD

**Issue by j-kelm** [utiasDSL/lsy_drone_racing#17]
When doing the following:
- starting drone with yaw = 0 and hovering
- rotating yaw set point to e.g. pi/2
- applying minor disturbances in roll or pitch
the emulated Mellinger controller fails to stabilize the drone. 

This behavior does not occur on the real drone and is related to the state and gyro values given to the emulated Mellinger controller (which would be obtained from the sensors on the real drone).

The fix involves using a different angle rotation order for providing the attitude to the Mellinger controller as well as rotating the angular velocity into the body frame (which did not happen this far).

**Comment by amacati** [comment]
I have looked at the PR and replicated the issue. Since I can't make changes to your PR I took the liberty to fix it on dev while adding tests and fixing other related issues in the physics module.
