### ISSUE TITLE
Index for observation looks wrong

### ISSUE THREAD

**Issue by danielsanjosepro** [utiasDSL/lsy_drone_racing#5]
I think there is an error with the indices when parsing the observations:
![1717427794](https://github.com/utiasDSL/lsy_drone_racing/assets/42489409/b402b51c-0bdd-45fb-aac2-c1a6ca419276)
I think the drone angle velocities start at 9 instead of 8

**Comment by amacati** [comment]
Ah right, I also noticed this when I went through the wrapper, but forgot to push a fix.
