### ISSUE TITLE
Action Space and Scaling in the wrapper

### ISSUE THREAD

**Issue by ge75xuv** [utiasDSL/lsy_drone_racing#8]
Hi @amacati ,

I struggle to understand the action space and action scaling in the DroneRacingWrapper. It says: 
"All values are scaled to [-1, 1]. Transformed back, x, y, z values of 1 correspond to 5m." I don't know how to interpret this.
The action is rescaled for the firmware by 1,1,1,pi and added to the current drone position. Then passed to the full state command of the firmware wrapper. So my question is, why did we not rescale the x,y,z by 0.2 instead of 1?

Secondly, to this logic, I assume, the action that the model learns has to be transformed afterwards as well. So when we use the trained RL model in the sim.py or elsewhere, the action suggested by the trained model has to be transformed in the same sense (rescaling and adding to the current position), right? e.g. when we do: 
```
action = model.predict(obs)
```
This action has to be transformed. I hope the question is clear
Thanks

**Comment by amacati** [comment]
It seems like the answer has resolved your question, so I'm closing the issue. Feel free to reopen it if you have additional questions related to this one.
